<script>
  import Orbitimages from './Orbitimages.vue'

  export default {
  	name: "Detail",
    props: ['searchText'],

  	components: {
  	  'orbitimages': Orbitimages
  	},

    data: function() {
      return {
        businessdetail: [
          {
           id: 1,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3,},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 4,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '一饭',
           address: '新天地三楼',
           number: '12345',
           count: 23,
           star: 3},
          {
           id: 2,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '二饭',
           address: '新天地三楼',
           number: '123456',
           count: 89,
           star: 4},
          {
           id: 3,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '三饭',
           address: '新天地三楼',
           number: '456789',
           count: 46,
           star: 2},
          {
           id: 4,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '四饭',
           address: '新天地三楼',
           number: '3456789',
           count: 294,
           star: 5},
          {
           id: 5,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '五饭',
           address: '新天地三楼',
           number: '1236789',
           count: 67,
           star: 2},
          {
           id: 6,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '六饭',
           address: '新天地三楼',
           number: '123459',
           count: 987,
           star: 5},
          {
           id: 7,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '七饭',
           address: '新天地三楼',
           number: '12349',
           count: 3,
           star: 1},
          {
           id: 8,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
            foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           money: 5,
           title: '八饭',
           address: '新天地三楼',
           number: '456789',
           count: 24,
           star: 2},
          {
           id: 9,
           picture: '../images/flower.jpg',
           comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             star: 3,
             money: 5,
             count: 133,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             comments: [
              {user: '123*****678',
              date: '2016-02-14',
              star: 4,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-05-03',
              star: 3,
              description: "良心商家~"},
              {user: '123*****678',
              date: '2015-12-14',
              star: 5,
              description: "好吃好吃好好吃！"},
              {user: '123*****678',
              date: '2016-04-07',
              star: 2,
              description: "一般般"}
             ],
             star: 3}
           ],
           title: '九饭',
           address: '新天地三楼',
           number: '16789',
           count: 109,
           star: 4}
        ],
        currentid: this.$route.params.bussinessId-1,
        username: 'iii',
        shopping_cart: [],
        address: '',
        tel: '',
        total: 0
      }
    },
    methods: {
      addFood: function(foodname, money, num) {
        var isFind = false;
          for (var i = 0; i < this.shopping_cart.length; i++) {
            if (this.shopping_cart[i].food_name == foodname) {
              this.shopping_cart[i].amount += num;
              this.total += num*money;
              isFind = true;
              break;
            }
          }
          if (!isFind) {
            var temp = {};
            temp.food_name = foodname;
            temp.price = money;
            temp.amount = num;
            this.total += temp.price*temp.amount;
            this.shopping_cart.push(temp);
          }
      },
      isValidate: function(event) {
        var address = $("#address").val();
        var tel = $("#tel").val();
        if (address == "" || tel == "") {
          return false;
        }
        var tel_reg = /^[1-9][0-9]{10}$/;
        if (tel_reg.test(tel)) {
          this.address = address;
          this.tel = tel;
          return true;
        } else alert("You should enter a valid telphone number.");
        event.preventDefault();
        return false;
      },
      emptyInput: function() {
        $("#address").val("");
        $("#tel").val("");
      }
    }
  }
</script>

<template>
<div>
  <orbitimages :bussiness-detail="businessdetail[currentid]"></orbitimages>
  <div class="row small-up-1 medium-up-2 large-up-4">
    <template v-for="item in businessdetail[currentid].foods | filterBy searchText in 'food_name'">
      <div class="column">

        <div class="reveal" :id="item.food_name" data-reveal>
          <h2>{{item.food_name}}</h2>
          <img :src="item.picture" />
          <div class="row food_detail_">
            <div class="column">{{item.food_name}}</div>
            <div class="column-6">
              <i v-for="n in item.star" class="fi-star yellow"></i><i v-for="n in (5-item.star)" class="fi-star gray"></i>
            </div>
            <div class="column price"><i class="fi-yen"></i> {{item.money}}</div>
            <div class="column count_detail">剩余<span class="item_count">{{item.count}}</span>份</div>
          </div>
          <div class="button expanded" data-open="order_again" v-on:click="addFood(item.food_name, item.money, 1)">加入购物车</div>
          <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
          </button>
          <ul class="show_comments accordion" data-accordion data-multi-expand="true">
             <li v-for="comment in item.comments" v-bind:class="[$index==0 ? 'is-active':'']" class="accordion-item" data-accordion-item>
               <a class="accordion-title">
                <span>{{comment.user}}</span>
                <i v-for="n in comment.star" class="fi-star yellow"></i><i v-for="n in (5-comment.star)" class="fi-star gray"></i>
                <span>{{comment.date}}</span>
               </a>
               <div class="description accordion-content" data-tab-content>{{comment.description}}</div>
             </li>
          </ul>
        </div>

        <a :data-open="item.food_name">
        <img class="thumbnail" :src="item.picture" /></a>
        <div class="row food_detail">
          <div class="column">{{item.food_name}}</div>
          <div class="column-6">
            <i v-for="n in item.star" class="fi-star yellow"></i><i v-for="n in (5-item.star)" class="fi-star gray"></i>
          </div>
          <div class="column price"><i class="fi-yen"></i> {{item.money}}</div>
        </div>
        <div class="button expanded" data-open="order_again" v-on:click="addFood(item.food_name, item.money, 1)">加入购物车</div>
        
      </div>
    </template>
    <div class="button order_button" data-open="addorder">去下单</div>
    <div class="reveal" id="order_again" data-reveal>
      <h2>成功加入购物车</h2>
      <div class="button expanded" data-close aria-label="Close modal">继续挑选食物</div>
      <div class="button expanded" data-open="addorder">完成啦~去下单</div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <form class="reveal" id="addorder" method="post" action="./" data-reveal>
      <div>
        <label>地址:
          <input type="text" id="address" name="address" required="required" placeholder="Your Address"></input>
        </label>
        <label>联系电话:
          <input type="tel" id="tel" name="tel" required="required" placeholder="Your Phone Number"></input>
        </label>
      </div>
      <div>
        <ul id="order_list">
          <li class="row order_head">
            <span class="column">食物名称</span>
            <span class="column">数量/份</span>
            <span class="column">单价/元</span>
            <span class="column">总价/元</span>
          </li>
          <template v-for="food in shopping_cart">
            <li class="row">
              <span class="column">{{food.food_name}}</span>
              <span class="column">{{food.amount}}</span>
              <span class="column"><i class="fi-yen"></i> {{food.price}}</span>
              <span class="column">{{food.amount}}x{{food.price}}={{food.amount*food.price}}</span>
            </li>
          </template>
          <li class="row">
            <span class="column small-3 order_head">合计:</span>
            <span class="column small-3 small-offset-6"><i class="fi-yen"></i> {{total}}</span>
          </li>
        </ul>
      </div>
      <div id="submit_button">
        <input class="button expanded" type="submit" v-on:click="isValidate($event)" value="提交订单"></input>
      </div>
      <button class="close-button" data-close aria-label="Close modal" type="button" v-on:click="emptyInput()">
        <span aria-hidden="true">&times;</span>
      </button>
    </form>
  </div>
  <!--<div class="row small-up- 1 medium-up-2">
    <div class="column">

    </div>
    <div class="colunm">
      <div class="bussiness-info" data-hide-for="small">
        <div class="row bussiness-info-banner">
          商家信息
        </div>
        <div class="row bussiness-info-detail">
          <dl>
            <dt>商家名称:</dt>
            <dd>{{business[currentid].title}}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>-->
</div>
</template>