<script>
  import Orbitimages from './Orbitimages.vue'

  export default {
  	name: "Detail",

  	components: {
  	  'orbitimages': Orbitimages
  	},

    data: function() {
      return {
        businessdetail: [
          {
           id: 1,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 4,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '一饭',
           number: '12345',
           count: 23,
           star: 3},
          {
           id: 2,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '二饭',
           number: '123456',
           count: 89,
           star: 4},
          {
           id: 3,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '三饭',
           number: '456789',
           count: 46,
           star: 2},
          {
           id: 4,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '四饭',
           number: '3456789',
           count: 294,
           star: 5},
          {
           id: 5,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '五饭',
           number: '1236789',
           count: 67,
           star: 2},
          {
           id: 6,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '六饭',
           number: '123459',
           count: 987,
           star: 5},
          {
           id: 7,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '七饭',
           number: '12349',
           count: 3,
           star: 1},
          {
           id: 8,
                      foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           money: 5,
           title: '八饭',
           number: '456789',
           count: 24,
           star: 2},
          {
           id: 9,
           foods: [
            {food_name: 'a',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 23,
             star: 3},
             {food_name: 'b',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 45,
             star: 3},
             {food_name: 'c',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 133,
             star: 3},
             {food_name: 'd',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 65,
             star: 3},
             {food_name: 'e',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3},
             {food_name: 'f',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 143,
             star: 3},
             {food_name: 'g',
             picture: '../images/flower.jpg',
             alt: 'flower',
             myurl: 'http://www.baidu.com',
             money: 5,
             count: 543,
             star: 3}
           ],
           title: '九饭',
           number: '16789',
           count: 109,
           star: 4}
        ],
        currentid: this.$route.params.bussinessId-1
      }
    }
  }
</script>

<template>
<div>
  <orbitimages></orbitimages>
  <!--<div class="row small-up- 1 medium-up-2">
    <div class="column">

    </div>
    <div class="colunm">
      <div class="bussiness-info" data-hide-for="small">
        <div class="row bussiness-info-banner">
          商家信息
        </div>
        <div class="row bussiness-info-detail">
          <dl>
            <dt>商家名称:</dt>
            <dd>{{business[currentid].title}}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>-->
  <div class="row small-up-1 medium-up-2 large-up-4">
    <template v-for="item in businessdetail[currentid].foods">
      <div class="column">
        <a v-bind:href="item.myurl">
        <img class="thumbnail" :src="item.picture" /></a>
        <h5>{{item.food_name}}</h5>
        <p>${{item.money}}</p>
        <a class="button expanded" v-bind:href="item.myurl">加入购物车</a>
      </div>
    </template>
  </div>
</div>
</template>