# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[(b'P', b'Phone'), (b'E', b'Email')], max_length=1)),
                ('nickname', models.CharField(max_length=20)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True, auto_now_add=True)),
                ('store_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('announcement', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('is_banned', models.CharField(choices=[(b'Y', b'yes'), (b'N', b'no')], default=b'N', max_length=1)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True, auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='bussiness.Seller')),
            ],
        ),
    ]
